[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600

lib_deps =
    adafruit/Adafruit AHTX0 @ ^2.0.5
    khoih-prog/MySQL_MariaDB_Generic @ ^1.7.2
lib_ignore =
    WiFi101
    WiFi101_Generic
    WiFiEspAT
    WiFiMulti_Generic
    WiFiNINA_Generic
    ESP8266_AT_WebServer
    ESP_AT_Lib
    Ethernet
    EthernetENC
    UIPEthernet
    WebServer_WT32_ETH01



